<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>NeoSimpleLogger</PackageId>
    <Version>1.2.4</Version>
    <Authors>ruzen42</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    <Description>An Simple Logger .NET library (for file and console)</Description>
    <PackageTags>dotnet, utility, logger</PackageTags>
    <RepositoryUrl>https://github.com/ruzen42/simple-logger</RepositoryUrl>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="icon.png" Pack="true" PackagePath="/" />
    <None Include="LICENSE" Pack="true" PackagePath=""/>
    <None Include="README.md" Pack="true" PackagePath=""/>
  </ItemGroup>

</Project>
