<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>SimpleLogger</PackageId>
    <Version>1.0</Version>
    <Authors>ruzen42</Authors>
    <Description>An Simple Logger .NET library</Description>
    <PackageTags>dotnet, utility, logger</PackageTags>
    <RepositoryUrl>https://github.com/ruzen42/simple-logger</RepositoryUrl>
    <PackageLicenseExpression>GPL</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="icon.png" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
